map_type:             costmap
obstacle_range:       2.5
raytrace_range:       3.0
transform_tolerance:  0.2
footprint:            [[0.35, 0.35], [0.35, -0.35], [-0.35, -0.35], [-0.35,0.35]]
#robot_radius:        0.0 
inflation_radius:     0.55
observation_sources:  laser_scan_sensor
laser_scan_sensor: {sensor_frame: center_laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}